version: "3.7"
services:

## Bitwarden - Password Vault
  bitwarden:
    container_name: bitwarden
    image: bitwardenrs/server
    restart: always
    networks:
      - traefik_proxy
#    ports:
#      - "8888:80"
    volumes:
      - $USERDIR/docker/bitwarden:/data
      - /var/log/docker:/var/log/docker
      - /etc/localtime:/etc/localtime:ro
    environment:
      - SIGNUPS_ALLOWED=false # Change to false after first login
      - INVITATIONS_ALLOWED=false
      - WEBSOCKET_ENABLED=false #true
      - LOG_FILE=/var/log/docker/bitwarden.log
      - SMTP_HOST=smtp.gmail.com
      - SMTP_FROM=$SMTP_EMAIL
      - SMTP_PORT=587
      - SMTP_SSL=true
      - SMTP_USERNAME=$SMTP_EMAIL
      - SMTP_PASSWORD=$SMTP_PASS
      - DOMAIN=https://bitwarden.$DOMAINNAME
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik_proxy
      ## HTTPS entrypoint
      - traefik.http.routers.bitwarden.entrypoints=https
      - traefik.http.routers.bitwarden.rule=Host(`bitwarden.$DOMAINNAME`)
      - traefik.http.routers.bitwarden.tls.certresolver=cloudflare
      ## Middlewares - Unique
      - traefik.http.routers.bitwarden.middlewares=bitwarden-headers
      - traefik.http.middlewares.bitwarden-headers.headers.SSLHost=bitwarden.$DOMAINNAME
      ## Middlewares - Chain
      - traefik.http.routers.bitwarden.middlewares=noauth-chain@file
      ## Services
      - traefik.http.routers.bitwarden.service=bitwarden
      - traefik.http.services.bitwarden.loadbalancer.server.port=80

#      - "traefik.hub.frontend.rule=Host:bitwarden.${DOMAINNAME};Path:/notifications/hub"
#      - "traefik.hub.port=3012"
#      - "traefik.hub.protocol=ws"

networks:
  traefik_proxy:
    external:
      name: traefik_proxy
