version: "3.7"
services:

## Glances - Container and System Monitor
  glances:
    container_name: glances
    image: nicolargo/glances
    pid: host
    restart: unless-stopped
    networks:
      - traefik_proxy
#    ports:
#      - "61208:61208"
    volumes:
      - glances_config:/glances/conf # Use this if you want to add a glances.conf file
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - GLANCES_OPT=-w
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik_proxy
      ## HTTPS entrypoint
      - traefik.http.routers.glances.entrypoints=https
      - traefik.http.routers.glances.rule=Host(`glances.$DOMAINNAME`)
      - traefik.http.routers.glances.tls.certresolver=cloudflare
      ## Middlewares - Unique
      - traefik.http.routers.glances.middlewares=glances-headers
      - traefik.http.middlewares.glances-headers.headers.SSLHost=glances.$DOMAINNAME
      ## Middlewares - Chain
      - traefik.http.routers.glances.middlewares=secure-chain@file
      ## Services
      - traefik.http.routers.glances.service=glances
      - traefik.http.services.glances.loadbalancer.server.port=61208

volumes:
  glances_config:

networks:
  traefik_proxy:
    external:
      name: traefik_proxy
