version: "3.7"
services:

## Handbrake - Video Converter
  handbrake:
    container_name: handbrake
    image: jlesage/handbrake
    restart: always
    networks:
      - traefik_proxy
#    ports:
#      - "5800:5800"
    volumes:
      - $USERDIR/docker/handbrake/config:/config:rw
      - /mnt/storage:/storage:ro # Data folder - can be anything
      - $USERDIR/dwnloads:/downloads:ro # Data folder - can be anything
      - $USERDIR/docker/handbrake/watch:/watch:rw # Watch folder
      - $USERDIR/docker/handbrake/output:/output:rw # Output folder
    environment:
      - USER_ID=$PUID
      - GROUP_ID=$PGID
      - TZ=${TZ}
      - UMASK=002
      - DISPLAY_WIDTH=1280
      - DISPLAY_HEIGHT=768
      - AUTOMATED_CONVERSION_PRESET=H.265 MKV 480p30
#      - AUTOMATED_CONVERSION_PRESET=H.265 MKV 1080p30
      - AUTOMATED_CONVERSION_FORMAT=mkv
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik_proxy
      ## HTTPS entrypoint
      - traefik.http.routers.handbrake.entrypoints=https
      - traefik.http.routers.handbrake.rule=Host(`handbrake.$DOMAINNAME`)
      - traefik.http.routers.handbrake.tls.certresolver=cloudflare
      ## Middlewares - Unique
      - traefik.http.routers.handbrake.middlewares=handbrake-headers
      - traefik.http.middlewares.handbrake-headers.headers.SSLHost=handbrake.$DOMAINNAME
      ## Middlewares - Chain
      - traefik.http.routers.handbrake.middlewares=secure-chain@file
      ## Services
      - traefik.http.routers.handbrake.service=handbrake
      - traefik.http.services.handbrake.loadbalancer.server.port=5800

networks:
  traefik_proxy:
    external:
      name: traefik_proxy
