version: "3.7"
services:

## Heimdall - Homepage
  heimdall:
    container_name: heimdall
    image: linuxserver/heimdall
    restart: always
    networks:
      - traefik_proxy
#    ports:
#      - "80:80"
    volumes:
      - $USERDIR/docker/heimdall:/config
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik_proxy
      ## HTTPS entrypoint
      - traefik.http.routers.heimdall.entrypoints=https
      - traefik.http.routers.heimdall.rule=Host(`heimdall.$DOMAINNAME`)
      - traefik.http.routers.heimdall.tls.certresolver=cloudflare
      ## Middlewares - Unique
      - traefik.http.routers.heimdall.middlewares=heimdall-headers
      - traefik.http.middlewares.heimdall-headers.headers.SSLHost=heimdall.$DOMAINNAME
      ## Middlewares - Chain
      - traefik.http.routers.heimdall.middlewares=secure-headers@file
      ## Services
      - traefik.http.routers.heimdall.service=heimdall
      - traefik.http.services.heimdall.loadbalancer.server.port=80

networks:
  traefik_proxy:
    external:
      name: traefik_proxy
