version: "3.7"
services:

## Mariadb – Database Server
  # Suggested procedure to create new databases:
  # Replace <these values>
  # docker exec -it mariadb mysql -uroot -p
  # CREATE DATABASE <database name> CHARACTER SET = utf8mb4 COLLATE = utf8mb4_general_ci;
  # GRANT ALL PRIVILEGES ON <database name>.* TO '<user>'@'<container>.traefik_proxy' IDENTIFIED BY 'Hippi99((';
  # FLUSH PRIVILEGES;
  # exit
  mariadb:
    container_name: mariadb
    image: linuxserver/mariadb
    restart: always
    networks:
      - traefik_proxy
#    ports:
#      - "3306:3306"
    volumes:
      - $USERDIR/docker/mariadb:/config
      - /etc/localtime:/etc/localtime:ro
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik_proxy
      ## TCP
      - traefik.tcp.routers.mariadb.entrypoints=mariadb-port
      - traefik.tcp.routers.mariadb.tls=true
      - traefik.tcp.routers.mariadb.rule=HostSNI(`*`)
      - traefik.tcp.routers.mariadb.service=mariadb
      - traefik.tcp.services.mariadb.loadbalancer.server.port=3306

## phpMyAdmin - WebUI for MariaDB
  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin
    restart: always
    depends_on:
      - mariadb
    networks:
      - traefik_proxy
#    ports:
#      - "80:80"
    environment:
#      - PMA_ARBITRARY=1 # Allows you to enter a database server hostname on login form
      - PMA_HOST=mariadb
      - PMA_USER=root
      - PMA_PASSWORD=$MYSQL_ROOT_PASSWORD
      - PMA_ABSOLUTE_URI=https://phpmyadmin.$DOMAINNAME
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik_proxy
      ## HTTPS entrypoint
      - traefik.http.routers.phpmyadmin.entrypoints=https
      - traefik.http.routers.phpmyadmin.rule=Host(`phpmyadmin.$DOMAINNAME`)
      - traefik.http.routers.phpmyadmin.tls.certresolver=cloudflare
      ## Middlewares - Unique
      - traefik.http.routers.phpmyadmin.middlewares=phpmyadmin-headers
      - traefik.http.middlewares.phpmyadmin-headers.headers.SSLHost=phpmyadmin.$DOMAINNAME
      ## Middlewares - Chain
      - traefik.http.routers.phpmyadmin.middlewares=secure-chain@file
      ## Services
      - traefik.http.routers.phpmyadmin.service=phpmyadmin
      - traefik.http.services.phpmyadmin.loadbalancer.server.port=80

networks:
  traefik_proxy:
    external:
      name: traefik_proxy
