version: "3.7"
services:

## Portainer - WebUI for Containers
  portainer:
    container_name: portainer
    image: portainer/portainer
    restart: always
    command: -H unix:///var/run/docker.sock
    networks:
      - traefik_proxy
#    ports:
#      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data # Change to local directory if you want to save/transfer config locally
    environment:
      - TZ=$TZ
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik_proxy
      ## HTTPS entrypoint
      - traefik.http.routers.portainer.entrypoints=https
      - traefik.http.routers.portainer.rule=Host(`portainer.$DOMAINNAME`)
      - traefik.http.routers.portainer.tls.certresolver=cloudflare
      ## Middlewares - Unique
      - traefik.http.routers.portainer.middlewares=portainer-headers
      - traefik.http.middlewares.portainer-headers.headers.SSLHost=portainer.$DOMAINNAME
      ## Middlewares - Chain
      - traefik.http.routers.portainer.middlewares=secure-chain@file
      ## Services
      - traefik.http.routers.portainer.service=portainer
      - traefik.http.services.portainer.loadbalancer.server.port=9000

volumes:
  portainer_data:

networks:
  traefik_proxy:
    external:
      name: traefik_proxy
