version: "3.3"
services:

## Portainer - WebUI for Containers
  portainer:
    container_name: portainer
    image: portainer/portainer
    restart: always
    command: -H unix:///var/run/docker.sock
    networks:
      - traefik_proxy
#    expose:
#      - "9000"
#    ports:
#      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data # Change to local directory if you want to save/transfer config locally
    environment:
      - TZ=$TZ
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik_proxy
      - traefik.http.routers.portainer.entrypoints=http
      - traefik.http.routers.portainer.rule=Host(`portainer.$DOMAINNAME`)

      - traefik.http.routers.portainer-secure.entrypoints=https
      - traefik.http.routers.portainer-secure.rule=Host(`portainer.$DOMAINNAME`)
      - traefik.http.routers.portainer-secure.tls.certresolver=cloudflare

      - "traefik.http.middlewares.test-auth.forwardauth.trustForwardHeader=true"
      - "traefik.http.middlewares.test-auth.forwardauth.Address=http://oauth:4181"
      - "traefik.http.middlewares.test-auth.forwardauth.authResponseHeaders=X-Forwarded-User, X-WebAuth-User"

      - "traefik.http.routers.portainer-secure.service=portainer-secure"
      - traefik.http.services.portainer-secure.loadbalancer.server.port=9000

      - "traefik.http.routers.portainer-secure.middlewares=secured"
      - "traefik.http.middlewares.secured.chain.middlewares=https-only,test-auth"
      - "traefik.http.middlewares.https-only.redirectscheme.scheme=https"


volumes:
  portainer_data:

networks:
  traefik_proxy:
    external:
      name: traefik_proxy
