version: "3.7"
services:

# Need to run with MongoDB

## Wekan - Open Source Kanban Board
  wekan:
    container_name: wekan
    image: wekanteam/wekan
    restart: always
    networks:
      - traefik_proxy
#    ports:
#      - "8080:8080"
    volumes:
      - /etc/localtime:/etc/localtime:ro
    environment:
      - MONGO_URL=mongodb://mongo:27017/wekan # //<mongo container name>:<mongo port>/<database name>
      - ROOT_URL=https://wekan.$DOMAINNAME
      - WITH_API=false
      - BROWSER_POLICY_ENABLED=true
      - TRUSTED_URL=https://wekan.$DOMAINNAME
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik_proxy
      ## HTTPS entrypoint
      - traefik.http.routers.wekan.entrypoints=https
      - traefik.http.routers.wekan.rule=Host(`wekan.$DOMAINNAME`)
      - traefik.http.routers.wekan.tls.certresolver=cloudflare
      ## Middlewares - Unique
      - traefik.http.routers.wekan.middlewares=wekan-headers
      - traefik.http.middlewares.wekan-headers.headers.SSLHost=wekan.$DOMAINNAME
      ## Middlewares - Chain
      - traefik.http.routers.wekan.middlewares=secure-chain-nocookie@file
      ## Services
      - traefik.http.routers.wekan.service=wekan
      - traefik.http.services.wekan.loadbalancer.server.port=8080

networks:
  traefik_proxy:
    external:
      name: traefik_proxy
